apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby-deployment-liveness
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dobby-service
  template:
    metadata:
      labels:
        app: dobby-service
    spec:
      containers:
      - name: dobby
        image: thecasualcoder/dobby
        livenessProbe:
          httpGet:
            path: /health
            port: 4444