---
apiVersion: v1
kind: Pod
metadata:
  name: dobby
spec:
  containers:
    - name: dobby
      image: thecasualcoder/dobby
      livenessProbe:
        httpGet:
          path: /health
          port: 4444
