apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dobby
  template:
    metadata:
      labels:
        app: dobby
    spec:
      containers:
      - name: dobby
        image: thecasualcoder/dobby:notready
        livenessProbe:
          httpGet:
            path: /health
            port: 4444
        readinessProbe:
          httpGet:
            path: /health
            port: 4444
