---
apiVersion: v1
kind: Pod
metadata:
  name: dobby
spec:
  containers:
    - name: dobby
      image: thecasualcoder/dobby
      readinessProbe:
        httpGet:
          path: /readiness
          port: 4444
