apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dobby
  template:
    metadata:
      labels:
        app: dobby
    spec:
      containers:
      - name: dobby
        image: thecasualcoder/dobby
        readinessProbe:
          httpGet:
            path: /readiness
            port: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: dobby
spec:
  selector:
    app: dobby
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4444