apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby-deployment-limits
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dobby-service
  template:
    metadata:
      labels:
        app: dobby-service
    spec:
      containers:
      - name: dobby
        image: thecasualcoder/dobby
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"